//
//  Dummy Data.swift
//  Pappea Driver
//
//  Created by Apple on 02/08/19.
//  Copyright © 2019 baps. All rights reserved.
//

import Foundation

// New booking request arrived from Peppea
/*
{
    "message" : "New booking request arrived from Peppea",
    "booking_info" : {
        "customer_info" : {
            "profile_image" : "assets\/images\/customer\/33\/76ebbc3e497e7fa9824522e2d4755649.jpeg",
            "address" : "Ahmedabad",
            "wallet_balance" : "0",
            "first_name" : "Bhavesh",
            "qr_code" : "assets\/images\/qrcode\/Y3VzdG9tZXJfMzM=.png",
            "last_name" : "Odedra",
            "device_type" : "ios",
            "miles_balance" : "0",
            "device_token" : "bcf924206f2b415848b9634f3a497fb2f2976e7d64ac395fc333bc4e205e3426",
            "user_type" : "passenger",
            "miles_exp_date" : "0000-00-00 00:00:00",
            "id" : "33",
            "created_at" : "2019-07-25 09:22:48",
            "status" : "1",
            "mobile_no" : "1144772255",
            "password" : "25d55ad283aa400af464c76d713c07ad",
            "rating" : "4.83",
            "referral_code" : "pepcs33Bha",
            "social_id" : "",
            "lng" : "72.5163024",
            "gender" : "male",
            "lat" : "23.0727213",
            "dob" : "1986-07-25",
            "social_type" : "",
            "remember_token" : "",
            "email" : "bhavesh@gmail.com",
            "trash" : "0"
        },
        "pickup_lng" : "72.516275224",
        "estimated_fare" : "48.73",
        "booking_type" : "book_now",
        "booking_time" : "1564746172",
        "status" : "pending",
        "customer_id" : "33",
        "dropoff_lat" : "23.0384171",
        "on_the_way" : "0",
        "driver_amount" : "",
        "extra_charge" : "0",
        "vehicle_type_id" : "1",
        "driver_id" : "0",
        "pickup_date_time" : "",
        "booking_fee" : "",
        "promocode" : "",
        "dropoff_location" : "Vastrapur Lake Vastrapur Lake, Vastrapur, Ahmedabad, Gujarat 380052",
        "pickup_time" : "",
        "company_amount" : "",
        "pickup_location" : "601, City Center, Opp. Shukan Mall, Science City Rd, Sola, Ahmedabad, Gujarat 380060, India",
        "dropoff_lng" : "72.5288016",
        "pickup_lat" : "23.072720367",
        "payment_status" : "",
        "id" : "329",
        "vehicle_type" : {
            "base_charge" : "5",
            "capacity" : "3",
            "updated_at" : "0000-00-00 00:00:00",
            "per_minute_charge" : "2",
            "description" : "",
            "name" : "mini",
            "commission" : "10",
            "base_km" : "0",
            "unselect_image" : "assets\/images\/vehicle\/1\/a4c1f5bff20886d38f6b924ec9ee182f.png",
            "per_km_charge" : "2",
            "customer_cancellation_fee" : "10",
            "sort" : "1",
            "created_at" : "0000-00-00 00:00:00",
            "base" : "0",
            "status" : "1",
            "charge" : "0",
            "image" : "assets\/images\/vehicle\/1\/fde8fa48f9b84e820e5a611c8a6fb76f.png",
            "id" : "1",
            "booking_fee" : "5",
            "driver_cancellation_fee" : "10",
            "trash" : "0",
            "extra_charge" : "0"
        },
        "payment_type" : "cash",
        "sub_total" : "",
        "no_of_passenger" : "1",
        "_id" : "5d4421bd93be7108fdd8da86",
        "tips" : "0",
        "arrived_time" : "",
        "card_id" : "0",
        "grand_total" : "",
        "tips_status" : "0",
        "distance" : "",
        "reference_id" : "",
        "duration_fare" : "",
        "accept_time" : "",
        "trip_duration" : "",
        "discount" : "",
        "cancel_by" : "",
        "tax" : "",
        "dropoff_time" : "",
        "base_fare" : "",
        "distance_fare" : "",
        "cancellation_charge" : ""
    }
}
*/

// ----------------------------------------------------------
// ----------------------------------------------------------

/*
The webservice call is for https://www.peppea.com/panel/api/driver_api/complete_trip and the params are
{
    "dropoff_lng" : "72.581901300",
    "booking_id" : "457",
    "dropoff_lat" : "23.0263517"
}
the response is
{
    "message" : "Trip completed successfully.",
    "data" : {
        "customer_info" : {
            "gender" : "male",
            "lng" : "72.5150017",
            "mobile_no" : "1144772255",
            "password" : "25d55ad283aa400af464c76d713c07ad",
            "rating" : "4.8",
            "profile_image" : "assets\/images\/customer\/33\/76ebbc3e497e7fa9824522e2d4755649.jpeg",
            "wallet_balance" : "0",
            "id" : "33",
            "first_name" : "Bhavesh",
            "device_type" : "ios",
            "created_at" : "2019-07-25 09:22:48",
            "social_id" : "",
            "last_name" : "Odedra",
            "email" : "bhavesh@gmail.com",
            "user_type" : "passenger",
            "remember_token" : "",
            "lat" : "23.0725732",
            "address" : "Ahmedabad",
            "miles_exp_date" : "2019-08-09 23:59:59",
            "referral_code" : "pepcs33Bha",
            "dob" : "1986-07-25",
            "miles_balance" : "5",
            "device_token" : "sdfsdfwrfw4rt34r53",
            "qr_code" : "assets\/images\/qrcode\/Y3VzdG9tZXJfMzM=.png",
            "status" : "1",
            "trash" : "0",
            "social_type" : ""
        },
        "cancellation_charge" : "",
        "estimated_fare" : "152.15",
        "customer_id" : "33",
        "tips_status" : "1",
        "dropoff_lng" : "72.581901300",
        "payment_status" : "",
        "fix_rate_id" : "0",
        "discount" : "0",
        "base_fare" : "10",
        "sub_total" : "41.58",
        "reference_id" : "",
        "driver_amount" : "77.42",
        "tips" : "40",
        "accept_time" : "1565272420",
        "pickup_lng" : "72.5164187",
        "booking_type" : "book_now",
        "pickup_time" : "1565272425",
        "pickup_location" : "Excellent WebWorld 203-206 City Center Opp Shukan Mall, Science City Rd, Science City, Sola, Ahmedabad, Gujarat 380060, India",
        "dropoff_location" : "Lal Darwaja Old City, Lal Darwaja, Ahmedabad, Gujarat 380001, India",
        "distance_fare" : "19.98",
        "status" : "completed",
        "dropoff_time" : "1565272434",
        "dropoff_lat" : "23.0263517",
        "vehicle_type" : {
            "id" : "1",
            "base_charge" : "10",
            "per_minute_charge" : "4",
            "base" : "0",
            "capacity" : "5",
            "base_km" : "1",
            "per_km_charge" : "4",
            "trash" : "0",
            "created_at" : "0000-00-00 00:00:00",
            "status" : "1",
            "name" : "Platinum",
            "customer_cancellation_fee" : "10",
            "extra_charge" : "5",
            "image" : "assets\/images\/vehicle\/2\/e9b9236c3fe883be92fb97e366ad4201.png",
            "description" : "",
            "unselect_image" : "assets\/images\/vehicle\/2\/4c5b5f2aa3256b19b03cb97d60818f36.png",
            "driver_cancellation_fee" : "10",
            "commission" : "10",
            "sort" : "2",
            "charge" : "0",
            "booking_fee" : "6",
            "updated_at" : "0000-00-00 00:00:00"
        },
        "pickup_lat" : "23.0726365",
        "tax" : "10.61",
        "id" : "457",
        "promocode" : "",
        "payment_response" : "",
        "extra_charge" : "5",
        "booking_time" : "1565272413",
        "distance" : "5.99376141",
        "driver_vehicle_info" : {
            "id" : "148",
            "plate_number" : "GJ-01-GH-2012",
            "car_right" : "assets\/images\/driver\/30\/b129a100af2f1afc1225c1128daaf0c6.jpeg",
            "vehicle_manufacturer" : "",
            "driver_id" : "30",
            "car_front" : "assets\/images\/driver\/30\/66d9b360ce32a0e8ebb16b70ab9b92da.jpeg",
            "company_id" : "1",
            "vehicle_model" : "Honda",
            "no_of_passenger" : "6",
            "year_of_manufacture" : "2019",
            "vehicle_type" : "1",
            "vehicle_manufacturer_id" : "0",
            "vehicle_model_id" : "0",
            "car_back" : "assets\/images\/driver\/30\/5c769edc9c92649ffc8658c0b516adc4.jpeg",
            "car_left" : "assets\/images\/driver\/30\/7c1a9dc6fcf4cdae2a2adddc3fa51dd1.jpeg"
        },
        "rent_type" : "standard_rate",
        "vehicle_type_id" : "1",
        "payment_type" : "cash",
        "no_of_passenger" : "1",
        "booking_fee" : "6",
        "driver_id" : "30",
        "arrived_time" : "",
        "cancel_by" : "",
        "pickup_date_time" : "",
        "trip_duration" : "9",
        "card_id" : "0",
        "grand_total" : "92.19",
        "duration_fare" : "0.6",
        "on_the_way" : "0",
        "driver_info" : {
            "first_name" : "Bhavesh",
            "bank_name" : "Kotak",
            "account_number" : "12345678920",
            "email" : "bhavesh@ymail.com",
            "account_holder_name" : "Bhavesh",
            "other_company_name" : "company",
            "id" : "30",
            "company_id" : "1",
            "work_with_other_company" : "1",
            "status" : "1",
            "referral_code" : "pepdr30bha",
            "lat" : "23.072633",
            "trash" : "0",
            "owner_name" : "",
            "profile_image" : "assets\/images\/driver\/30\/f44722c7aa57710afbb399f51a6d721c.jpg",
            "wallet_balance" : "-143.5",
            "lng" : "72.516421",
            "payment_method" : "cash",
            "state" : "",
            "country" : "",
            "bank_branch" : "Ahmadabad",
            "owner_mobile_no" : "",
            "dob" : "1986-07-16",
            "busy" : "0",
            "duty" : "1",
            "remember_token" : "",
            "qr_code" : "assets\/images\/qrcode\/ZHJpdmVyXzMw.png",
            "password" : "25d55ad283aa400af464c76d713c07ad",
            "mobile_no" : "1144772255",
            "last_name" : "Odedara",
            "city" : "",
            "device_type" : "ios",
            "gender" : "male",
            "driver_role" : "driver",
            "vehicle_type" : "1",
            "owner_email" : "",
            "verify" : "1",
            "address" : "Bhavesh",
            "device_token" : "b3727bb3480fdeb4883aea09693a14bef22287f877781e4231578c683203932b",
            "car_type" : "own",
            "invite_code" : "",
            "created_at" : "2019-07-16 14:00:04",
            "rating" : "0"
        },
        "request_id" : "",
        "company_amount" : "14.77"
    },
    "status" : true
}
*/
